### ISSUE TITLE
Braintree v.zero support

### ISSUE THREAD

**Issue by alepore** [spree/spree_gateway#231]
I'm opening this issue because Braintree was always one of the better supported gateways and the "v.zero" (javascript) integration is really what people should use now.
Optional 3DSecure support is also very important.

I'm doing some tests and i also saw some fork work by @kamul @allisonlarson @acreilly, hope this issue can help some sort of coordination for future PRs ;)

**Comment by kamui** [comment]
@allisonlarson and I are working on adding support for a Braintree v.zero, here are the repos we're current working in, it'll be squashed when it's done: https://github.com/bonobos/spree_gateway/tree/2-2-braintree-v-zero and https://github.com/bonobos/active_merchant/tree/braintree-v-zero

We're building this as a new `active_merchant` gateway, since extending the current one didn't make sense (too much code branching to support and use of deprecated APIs) and we also made a new `spree_gateway` to match.

We've confirmed that creating a customer profile and authorization/sale/purchase work and we're now writing active_merchant specs. We got the `spree_gateway` specs passing (cloned from Braintree blue and altered), but the specs weren't great to begin with.

**Comment by kamui** [comment]
Unfortunately, we're abandoning our effort to add v.zero support to `active_merchant` and `spree_gateway`. The reason is actually 2 fold:

1. As we were building support into`active_merchant`, we realized that it didn't really make sense. The idea of `active_merchant` is a single API in which you can swap out many different gateways for common payment related functions. v.zero has a very different API because it can accept a nonce or a token, and  never a credit card. So you can't easily swap out v.zero gateway for another gateway. `spree_gateway` is basically a wrapper around `active_merchant`, so if decided to add a spree v.zero gateway, it makes more sense to do it in a separate gem rather than bundle it in this one.

2. We're very close to switching from spree to https://github.com/solidusio/solidus (a spree fork), so as we decided to create a braintree gateway gem, we decided we might as well do it for solidus instead. This gem is mostly done and we'll be open sourcing it shortly (days, not weeks away).

That said, those 2 branches we linked had most of the work already done, so anyone's free to pick that up if they want to continue adding v.zero support in `active_merchant` and `spree_gateway`.

The other option is to wait for our solidus braintree gateway gem to be released, since solidus 1.0 doesn't deviate too far from spree 2.4, it might be worth waiting for that and porting that gem to spree. It'll definitely be easier to work with because there's less layers of abstraction.

**Comment by alepore** [comment]
thanks for the detailed updates @kamui !
i'll be on this v.zero stuff in a few weeks and will take a look to your new gem, a spree port should not be too complex.
